name: CI - SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dependencies (if needed)
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      # Build C++ project
      - name: Build C++ project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      # Run tests (if available, else ignore failure)
      - name: Run tests
        run: |
          cd build
          ctest || true

      # SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONARQUBE: ${{ secrets.SONARQUBE }}
