name: CI - SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential unzip wget

      # Download Sonar build-wrapper
      - name: Download build-wrapper
        run: |
          wget -q https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip -q build-wrapper-linux-x86.zip
          echo "${PWD}/build-wrapper-linux-x86" >> $GITHUB_PATH

      # Build with g++ wrapped
      - name: Build with build-wrapper
        run: |
          mkdir -p build
          build-wrapper-linux-x86-64 --out-dir build/bw-output \
            g++ -std=c++17 -Wall -O2 -Iinclude -o build/app src/*.cpp


      # Run SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
