name: CI - SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Build C++ project using g++
      - name: Build C++ project
        run: |
          g++ -std=c++17 -O2 -Wall -Iinclude -o app src/*.cpp

      # Skip running app since it's interactive CLI
      - name: Skip execution
        run: echo "Skipping execution (program is interactive CLI)"

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
