name: CI - SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake unzip wget

      # Download build-wrapper
      - name: Download build-wrapper
        run: |
          wget -q https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip -q build-wrapper-linux-x86.zip
          echo "${PWD}/build-wrapper-linux-x86" >> $GITHUB_PATH

      # Build C++ project with build-wrapper
      - name: Build with build-wrapper
        run: |
          mkdir -p build
          cd build
          cmake ..
          # wrap make with build-wrapper
          build-wrapper-linux-x86-64 --out-dir bw-output make -j$(nproc)

      # Run SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONARQUBE: ${{ secrets.SONARQUBE }}
