name: CI - SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install build tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Build C++ project (src + include)
      - name: Build C++ project
        run: |
          g++ -std=c++17 -O2 -Wall -Iinclude -o app src/*.cpp

      # Skip running binary since it's interactive
      - name: Skip program execution
        run: echo "Skipping execution (program is interactive CLI)"

      # SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONARQUBE: ${{ secrets.SONARQUBE }}
