name: CI - SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install build tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Build C++ project using g++
      - name: Build C++ project
        run: |
          g++ -std=c++17 -O2 -Wall -o app main.cpp

      # Run app or tests (optional, won't fail if missing)
      - name: Run program/tests
        run: |
          ./app || true

      # SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONARQUBE: ${{ secrets.SONARQUBE }}
